#cloud-config

bootcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list'
  - wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /etc/apt/keyrings/grafana.gpg > /dev/null
  - echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | tee -a /etc/apt/sources.list.d/grafana.list

package_update: true
#package_upgrade: true

#download packages
packages:
  - neofetch
  - htop
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - lsb-release
  - adduser
  - libfontconfig1
  - musl
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - grafana

#correct MTU for docker
write_files:
- path: /etc/docker/daemon.json
  content: |
    {
      "mtu": 1442
    }

#creating Users and adding them to docker group
users:
  - name: Mallory
    groups: [docker]
    shell: /bin/bash
    passwd: $6$mQV0QXqaavPXrc$kjNge.mkrNBnDiVomO2rBtRwUzxVuZ/KZUaOrJHOOfv7FVzmXbOyz4vyEK7JcwpMciSnKVWfdpWwaSxh.CbF8.
    lock_passwd: false
  - name: Eve
    groups: [docker]
    shell: /bin/bash
    passwd: $6$mQV0QXqaavPXrc$kjNge.mkrNBnDiVomO2rBtRwUzxVuZ/KZUaOrJHOOfv7FVzmXbOyz4vyEK7JcwpMciSnKVWfdpWwaSxh.CbF8.
    lock_passwd: false

#restart docker and start grafana (also adds them to start at boot)
runcmd:
  - systemctl restart docker
  - systemctl enable docker.service
  - systemctl enable containerd.service
  - systemctl start grafana-server
  - systemctl enable grafana-server.service